/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import Services.IServiceBan;
import Services.ServiceBan;
import ViewModels.BanView;
import java.awt.Color;
import java.util.List;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucif
 */
public class ChuyenBan extends javax.swing.JDialog {

    int a;
    int getID;
    IServiceBan svsBan = new ServiceBan();
    /**
     * Creates new form NewJDialog
     */
    private FrmViewMainPage banhang;

    public ChuyenBan(java.awt.Frame parent, boolean modal, int kieu, int id) {
        super(parent, modal);
        a = kieu;
        getID = id;
        initComponents();
        banhang = (FrmViewMainPage) parent;
        loadTableBan(svsBan.findByStatus(kieu));
    }

    void loadTableBan(List<BanView> bv) {
        DefaultTableModel tbl = (DefaultTableModel) tbl_chuyenBan.getModel();
        tbl.setRowCount(0);
        for (BanView x : bv) {
            tbl.addRow(new Object[]{
                x.getMaBan(),
                x.getTrangThai() == 1 ? "Hoạt động" : "Trống"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_chuyenBan = new javax.swing.JTable();
        btn_xacNhan = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_chuyenBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã bàn", "Trạng thái", "Mã hóa đơn"
            }
        ));
        tbl_chuyenBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_chuyenBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_chuyenBan);

        btn_xacNhan.setText("Xác nhận");
        btn_xacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacNhanActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btn_xacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_chuyenBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_chuyenBanMouseClicked
        int index = tbl_chuyenBan.getSelectedRow();// TODO add your handling code here:
    }//GEN-LAST:event_tbl_chuyenBanMouseClicked

    private void btn_xacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacNhanActionPerformed
        if (a == 0) {
            int index = tbl_chuyenBan.getSelectedRow();
            int idBan = Integer.parseInt(tbl_chuyenBan.getValueAt(index, 0).toString().substring(1));
            svsBan.chuyenBan(getID, idBan);
        } else {
            int index = tbl_chuyenBan.getSelectedRow();
            int idBan = Integer.parseInt(tbl_chuyenBan.getValueAt(index, 0).toString().substring(1));
            svsBan.gopBan(getID, idBan);
        }
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xacNhanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_xacNhan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_chuyenBan;
    // End of variables declaration//GEN-END:variables
}
