/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Repositories.ImplThongke;
import Repositories.InterfaceThongke;
import ViewModels.thongkeCombo;
import ViewModels.thongkeSanPham;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repositories.ImplBangHoaDonChiTiet;
import repositories.InterfaceBangHoaDonChiTiet;

/**
 *
 * @author ADMIN
 */
public class JpanelThongke extends javax.swing.JPanel {

    /**
     * Creates new form JpanelThongke
     */
    InterfaceThongke TkDService = new ImplThongke();
    DefaultTableModel _tablcb = new DefaultTableModel();
    DefaultTableModel _tablsp = new DefaultTableModel();
    InterfaceBangHoaDonChiTiet hdct = new ImplBangHoaDonChiTiet();
  DecimalFormat fommater = new DecimalFormat("###, ###, ###");
    public JpanelThongke() {
        initComponents();
    }

    void loaddatasp(List<thongkeSanPham> list) {

        _tablsp = (DefaultTableModel) tblsp.getModel();
        _tablsp.setRowCount(0);
        int stt = 1;
        for (thongkeSanPham s : list) {
            _tablsp.addRow(new Object[]{stt++, s.getMaSp(), s.getTensp(), s.getGiaban(), s.getSoluong()});
        }
    }

    void loaddatacb(List<thongkeCombo> list) {
        _tablcb = (DefaultTableModel) tblcb.getModel();
        _tablcb.setRowCount(0);
        int stt = 1;
        for (thongkeCombo s : list) {
            _tablcb.addRow(new Object[]{stt++, s.getmaCombo(), s.gettencombo(), s.getGiaban(), s.getSoluong()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBieudo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        date2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        loctheoKhoang = new javax.swing.JButton();
        datengay = new com.toedter.calendar.JDateChooser();
        jchooseyear = new com.toedter.calendar.JYearChooser();
        loctheongay = new javax.swing.JButton();
        loctheonam = new javax.swing.JButton();
        loctheothang = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        homnay = new javax.swing.JButton();
        jchooseMonth = new com.toedter.calendar.JMonthChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcb = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblDoanhthu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblHoadon = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblTongSp = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblsp = new javax.swing.JTable();

        pnBieudo.setBorder(javax.swing.BorderFactory.createTitledBorder("Biểu đồ"));

        javax.swing.GroupLayout pnBieudoLayout = new javax.swing.GroupLayout(pnBieudo);
        pnBieudo.setLayout(pnBieudoLayout);
        pnBieudoLayout.setHorizontalGroup(
            pnBieudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        pnBieudoLayout.setVerticalGroup(
            pnBieudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jLabel1.setText("Từ ngày");

        jLabel2.setText("Đến ngày");

        loctheoKhoang.setText("Lọc");
        loctheoKhoang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loctheoKhoangActionPerformed(evt);
            }
        });

        loctheongay.setText("Theo ngày ");
        loctheongay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loctheongayActionPerformed(evt);
            }
        });

        loctheonam.setText("Theo năm ");
        loctheonam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loctheonamActionPerformed(evt);
            }
        });

        loctheothang.setText("Theo tháng ");
        loctheothang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loctheothangActionPerformed(evt);
            }
        });

        jButton4.setText("Xuất ");

        homnay.setText("Hôm nay");
        homnay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homnayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchooseyear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(datengay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loctheongay, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchooseMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loctheothang, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(homnay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loctheoKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loctheonam))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loctheoKhoang)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datengay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loctheongay, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(homnay))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loctheothang)
                            .addComponent(loctheonam)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchooseMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchooseyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        tblcb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã combo", "Tên combo", "Đơn giá ", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(tblcb);

        jLabel3.setText("Doanh Thu : ");

        lblDoanhthu.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblDoanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDoanhthu))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel5.setText("Tổng hóa đơn : ");

        lblHoadon.setText("jLabel4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblHoadon))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel7.setText("Tổng sản phẩm đã bán : ");

        lblTongSp.setText("jLabel4");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lblTongSp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTongSp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm ", "Đơn giá ", "Số lượng"
            }
        ));
        jScrollPane3.setViewportView(tblsp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(541, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnBieudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(pnBieudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loctheoKhoangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loctheoKhoangActionPerformed
        // TODO add your handling code here:
        
        Calendar cal1 = Calendar.getInstance();
            Calendar cal2 = Calendar.getInstance();
           
            if(date1.getDate() == null || date2.getDate() == null){
                System.out.println("null ");
                 JOptionPane.showMessageDialog(this, "Không được null !");
                return;
            }
//             if (!date1.getDateFormatString().equals(date1.getDate())){
//                JOptionPane.showMessageDialog(this, "Không đúng định dạng ngày ");
//                return;
//            } 
            
             cal1.setTime(date1.getDate());
            cal2.setTime(date2.getDate());
            if(cal1.after(cal2)){
                JOptionPane.showMessageDialog(this, "Không được chọn ngày bắt đầu < ngày khết thúc!");
                return;
            }
            
        if (TkDService.listdatatheokhoang(date1.getDate(), date2.getDate()) == null) {
            lblDoanhthu.setText(String.valueOf(0));
            lblHoadon.setText(String.valueOf(0));
            lblTongSp.setText(String.valueOf(0));       
            _tablcb.setRowCount(0);
            _tablsp.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Không có dữ liệu trong ngày ");
            return;
        }

      
        
        lblDoanhthu.setText(String.valueOf(fommater.format(TkDService.listdatatheokhoang(date1.getDate(), date2.getDate()).get(0).getTongtien())) + "VNĐ");
        lblHoadon.setText(String.valueOf(TkDService.listdatatheokhoang(date1.getDate(), date2.getDate()).get(0).getTonghd()));
        lblTongSp.setText(String.valueOf(TkDService.listdatatheokhoang(date1.getDate(), date2.getDate()).get(0).getTongsp()));
        TkDService.setDataKhoang(pnBieudo, date1.getDate(), date2.getDate());
        loaddatasp(TkDService.thongkesptheokhoang(date1.getDate(), date2.getDate()));
        loaddatacb(TkDService.thongkecbtheokhoang(date1.getDate(), date2.getDate()));
    }//GEN-LAST:event_loctheoKhoangActionPerformed

    private void loctheongayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loctheongayActionPerformed
        // TODO add your handling code here:
         if(datengay.getDate() == null ){        
                 JOptionPane.showMessageDialog(this, "Không được null !");
                return;
            }
        if (TkDService.listdatatheongay(datengay.getDate()) == null) {
            lblDoanhthu.setText(String.valueOf(0));
            lblHoadon.setText(String.valueOf(0));
            lblTongSp.setText(String.valueOf(0));
            TkDService.setDatangaynull(pnBieudo, datengay.getDate());
            _tablcb.setRowCount(0);
            _tablsp.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Không có dữ liệu trong ngày ");
            return;
        }

        lblDoanhthu.setText(String.valueOf(TkDService.listdatatheongay(datengay.getDate()).get(0).getTongtien()));
        lblHoadon.setText(String.valueOf(TkDService.listdatatheongay(datengay.getDate()).get(0).getTonghd()));
        lblTongSp.setText(String.valueOf(TkDService.listdatatheongay(datengay.getDate()).get(0).getTongsp()));
        TkDService.setDataNgay(pnBieudo, datengay.getDate());
        loaddatasp(TkDService.thongkesptheongay(datengay.getDate()));
        loaddatacb(TkDService.thongkecbtheongay(datengay.getDate()));
    }//GEN-LAST:event_loctheongayActionPerformed

    private void loctheothangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loctheothangActionPerformed
        // TODO add your handling code here:
        int thang = jchooseMonth.getMonth() + 1;
        int nam = jchooseyear.getYear();
        if (TkDService.listdatatheothang(thang, nam) == null) {
            lblDoanhthu.setText(String.valueOf(0));
            lblHoadon.setText(String.valueOf(0));
            lblTongSp.setText(String.valueOf(0));
//            TkDService.setDatanull(pnBieudo,);
            _tablcb.setRowCount(0);
            _tablsp.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Không có dữ liệu trong ngày ");
            return;
        }

        lblDoanhthu.setText(String.valueOf(TkDService.listdatatheothang(thang, nam).get(0).getTongtien()));
        lblHoadon.setText(String.valueOf(TkDService.listdatatheothang(thang, nam).get(0).getTonghd()));
        lblTongSp.setText(String.valueOf(TkDService.listdatatheothang(thang, nam).get(0).getTongsp()));
        TkDService.setDataThang(pnBieudo, thang, nam);
        loaddatasp(TkDService.thongkesptheothang(thang, nam));
        loaddatacb(TkDService.thongkecbtheothang(thang, nam));

    }//GEN-LAST:event_loctheothangActionPerformed

    private void loctheonamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loctheonamActionPerformed
        // TODO add your handling code here:
        int nam = jchooseyear.getYear();
        System.out.println(nam);
        if (TkDService.listdatatheonam(nam) == null) {
            lblDoanhthu.setText(String.valueOf(0));
            lblHoadon.setText(String.valueOf(0));
            lblTongSp.setText(String.valueOf(0));
//            TkDService.setDatanull(pnBieudo);
            _tablcb.setRowCount(0);
            _tablsp.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Không có dữ liệu trong ngày ");
            return;
        }

        lblDoanhthu.setText(String.valueOf(TkDService.listdatatheonam(nam).get(0).getTongtien()));
        lblHoadon.setText(String.valueOf(TkDService.listdatatheonam(nam).get(0).getTonghd()));
        lblTongSp.setText(String.valueOf(TkDService.listdatatheonam(nam).get(0).getTongsp()));
        TkDService.setDataNam(pnBieudo, nam);
        loaddatasp(TkDService.thongkesptheonam(nam));
        loaddatacb(TkDService.thongkecbtheonam(nam));

    }//GEN-LAST:event_loctheonamActionPerformed

    private void homnayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homnayActionPerformed
        // TODO add your handling code here:
 Date date = java.util.Calendar.getInstance().getTime();
        if (TkDService.listdatatheongay(date) == null) {
            lblDoanhthu.setText(String.valueOf(0));
            lblHoadon.setText(String.valueOf(0));
            lblTongSp.setText(String.valueOf(0));
           
            TkDService.setDatangaynull(pnBieudo, date);
            _tablcb.setRowCount(0);
            _tablsp.setRowCount(0);

            return;
        }

        lblDoanhthu.setText(String.valueOf(TkDService.listdatatheongay(date).get(0).getTongtien()));
        lblHoadon.setText(String.valueOf(TkDService.listdatatheongay(date).get(0).getTonghd()));
        lblTongSp.setText(String.valueOf(TkDService.listdatatheongay(date).get(0).getTongsp()));
        TkDService.setDataNgay(pnBieudo, date);
        loaddatasp(TkDService.thongkesptheongay(date));
        loaddatacb(TkDService.thongkecbtheongay(date));

        
    }//GEN-LAST:event_homnayActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private com.toedter.calendar.JDateChooser datengay;
    private javax.swing.JButton homnay;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JMonthChooser jchooseMonth;
    private com.toedter.calendar.JYearChooser jchooseyear;
    private javax.swing.JLabel lblDoanhthu;
    private javax.swing.JLabel lblHoadon;
    private javax.swing.JLabel lblTongSp;
    private javax.swing.JButton loctheoKhoang;
    private javax.swing.JButton loctheonam;
    private javax.swing.JButton loctheongay;
    private javax.swing.JButton loctheothang;
    private javax.swing.JPanel pnBieudo;
    private javax.swing.JTable tblcb;
    private javax.swing.JTable tblsp;
    // End of variables declaration//GEN-END:variables
}
