/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Application.Login;
import DomainModel.Nhanvien;
import Services.ServiceNhanVien;
import ViewModels.NhanvienView;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import repositories.ImplBangNhanVien;
import repositories.InterfaceBangNhanVien;

/**
 *
 * @author ADMIN
 */
public class JpanelDoimatkhau extends javax.swing.JPanel {

    /**
     * Creates new form JpanelDoimatkhau
     */
      ServiceNhanVien nvService = new ServiceNhanVien();
      InterfaceBangNhanVien daonv;
    public JpanelDoimatkhau() {
        initComponents();
        daonv = new ImplBangNhanVien();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtconfirm = new javax.swing.JPasswordField();
        txtMKcu = new javax.swing.JPasswordField();
        txtMKMoi = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btndoimk = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Mật khẩu cũ");

        jLabel2.setText("Mật khẩu mới");

        btndoimk.setText("Đổi mật khẩu ");
        btndoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoimkActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Đổi mật khẩu ");

        jLabel4.setText("Xác nhận mật khẩu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMKcu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btndoimk)
                                .addComponent(txtconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(414, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMKcu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addComponent(btndoimk)
                .addGap(152, 152, 152))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoimkActionPerformed
       

        if (check()) {
             Nhanvien nv = new Nhanvien();
        nv = daonv.login( Login.getCurrentUser().getTaiKhoan().trim(), String.valueOf(txtMKcu.getPassword()).trim());
            nv.setMatKhau(String.valueOf(txtMKMoi.getPassword()));
            daonv.update(nv);
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
            return;
        }

        
    }//GEN-LAST:event_btndoimkActionPerformed

boolean check() {
        String matkhau = new String(txtMKcu.getPassword());
        String matkhaumoi = new String(txtMKMoi.getPassword());
        String xacnhanmk = new String(txtconfirm.getPassword());
        String mk = "";

        if (matkhau.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu cũ!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            txtMKcu.requestFocus();
            return false;

        }
        if (matkhau.trim().equals(Login.getCurrentUser().getMatKhau().trim()) == false) {
             JOptionPane.showMessageDialog(this, "Sai mật khẩu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            txtconfirm.requestFocus();
            return false;
        }

        if (matkhaumoi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu mới!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            txtMKMoi.requestFocus();
            return false;

        }
        if (matkhaumoi.length() < 4 || matkhaumoi.length() > 20) {

            JOptionPane.showMessageDialog(this, "Mật khẩu phải từ 6 đến 20 kí tự");
            return false;
        }

        if (xacnhanmk.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            txtconfirm.requestFocus();
            return false;
        }
        if (!matkhaumoi.equals(xacnhanmk)) {
            JOptionPane.showMessageDialog(this,  "Mật khẩu không khớp", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            txtconfirm.requestFocus();
            return false;
        }

        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndoimk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtMKMoi;
    private javax.swing.JPasswordField txtMKcu;
    private javax.swing.JPasswordField txtconfirm;
    // End of variables declaration//GEN-END:variables
}
